#--- python mode ---

import os
import sys
import platform

env = Environment()

include_path = ['..', '../..']
lib_path = ['../../../build']
libs = ['gtest', 'gtest_main', 'cpp_util', 'pthread']

# platform for mac
if platform.system() == 'Darwin':
    include_path += [
        '/usr/local/include/mysql',
        '../../../gtest/gtest_64'
    ]
    env.Replace(CXX='/usr/local/bin/g++-4.8')
else:
    include_path += [
        '/usr/include/mysql',
        '../../../gtest/gtest_32'
    ]
    env.Replace(CXX='/usr/bin/g++')

# use gtest lib_32 or lib_64
if platform.architecture()[0] == '64bit':
    lib_path += ['../../../gtest/gtest_64/lib']
else:
    lib_path += ['../../../gtest/gtest_32/lib']

# set environment variables
env.Append(CPPPATH=Dir(include_path))
env.Append(LIBPATH=Dir(lib_path))
env.Append(LIBS=Dir(libs))
env.Append(CXXFLAGS='-Wall -g -O2 -fPIC -DLOGGER_LEVEL=LL_INFO')

# build
program = env.Program(
    target='UnitTest', 
    source=['mysqlClientTest.cpp'],
    LIBPATH=lib_path
)

ld_library_path_name = 'LD_LIBRARY_PATH'
if platform.system() == 'Darwin':
    ld_library_path_name = 'DYLD_LIBRARY_PATH'
action = '%s=.:../../../build %s' % (ld_library_path_name, program[0].abspath)
test_alias = Alias('test', [program], action)
AlwaysBuild(test_alias)
