Import('env')

objs = []
subdirs = ['common', 'file_util', 'log', 'mysql', 'string_util', 'thread']

for dir in subdirs:
    o = SConscript('%s/SConscript' % dir)
    objs.append(o)

libcpp_util = env.SharedLibrary(
    'cpp_util', objs
)

env.Install('../build', libcpp_util)
