#--- python mode ---

import os
Import('env')
env = env.Clone()

cpps = []
subdirs = ['common', 'file_util', 'log', 'mysql', 'string_util', 'thread_pool']

for dir in subdirs:
    obj = SConscript('%s/SConscript' % dir)
    cpps.append(obj)

Return('cpps')
